### ISSUE TITLE
Add relevent algorithms in different languages

### ISSUE THREAD

**Issue by Rahulwadhwa157** [Rahulwadhwa157/Algorithms-at-one-place#1]

**Comment by Cursed-Ninja** [comment]
Hey I want to contribute to adding algorithms for CPP. Can you assign it to me?

**Comment by ShaurabhTiwari** [comment]
I've created some of the codes and creating the rest

**Comment by amanydv72** [comment]
Hey Rahul,
I have already done with code, plz assign it to me
